name = "GreenComply EU"
client_id = "73383cd5508ddf57dec21cf62a6b8de0"
application_url = "https://greencomply.jobspic.com"
embedded = false

[build]

[auth]
redirect_urls = [
  "https://greencomply.jobspic.com/api/auth/callback"
]

[webhooks]
api_version = "2026-07"

[app_proxy]
url = "https://greencomply.jobspic.com/apps/eu-suite"
subpath = "eu-suite"
prefix = "apps"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders,read_customers,write_customers,read_content,write_content"
